apiVersion: v1
kind: Namespace
metadata:
  name: autoapi
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: podinfo-autoapi
  namespace: default
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-token
        key: PULUMI_ACCESS_TOKEN
  stack: squaremo/podinfo/autoapi
  gitRepo:
    projectRepo: https://github.com/squaremo/pulumi-flux-hack
    branch: refs/heads/main
  repoDir: ./pulumi
  config:
    namespace: autoapi # this tells the program to deploy to the namespace "autoapi"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulumi-stack
  namespace: autoapi
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pulumi-stack
  namespace: autoapi
subjects:
- kind: ServiceAccount
  name: pulumi-kubernetes-operator
  namespace: default
roleRef:
  kind: Role
  name: pulumi-stack
  apiGroup: rbac.authorization.k8s.io
---
