apiVersion: v1
kind: Namespace
metadata:
  name: flux
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pulumi-flux-hack
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/squaremo/pulumi-flux-hack
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: podinfo-flux
  namespace: default
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-token
        key: PULUMI_ACCESS_TOKEN
  stack: squaremo/podinfo/flux
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    name: pulumi-flux-hack
  repoDir: ./pulumi
  config:
    namespace: flux # this tells the program to deploy to the namespace "flux"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulumi-stack
  namespace: flux
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pulumi-stack
  namespace: flux
subjects:
- kind: ServiceAccount
  name: pulumi-kubernetes-operator
  namespace: default
roleRef:
  kind: Role
  name: pulumi-stack
  apiGroup: rbac.authorization.k8s.io
---

