apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: podinfo-autoapi
  namespace: default
spec:
  envRefs:
    PULUMI_ACESS_TOKEN:
      type: secret
      secret:
        name: pulumi-token
        key: PULUMI_ACCESS_TOKEN
  stack: squaremo/podinfo/autoapi
  gitRepo:
    projectRepo: https://github.com/squaremo/pulumi-flux-hack
    branch: refs/heads/main
  repoDir: ./pulumi
  config:
    namespace: autoapi # this tells the program to deploy to the namespace "autoapi"
